TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#DB += DB += xxx.db

DB += ADAM_4018_chan.db
DB += ADAM_4018.db
DB += Agilent_E3631A.db
DB += Alcatel_ACS1000.db
DB += Alcatel_ACS2000.db
DB += BK9130.db
DB += BK9173B.db
DB += CPSyringe.db
DB += cyberAmp.db
DB += deviceCmdReply.db
DB += Digitel.db
DB += eMike.db
DB += Encoder_AD4.db
DB += Eurotherm2k.db
DB += Eurotherm.db
DB += Federal.db
DB += HeidAWE1024.db
DB += heidND261.db
DB += HeidVRZ460_encoder.db
DB += HG-100.db
DB += HuberDMC9200.db
DB += HuberDMC9200Init.db
DB += iSeries.db
DB += JenaNV40.db
DB += Keithley2kDMM20.db
DB += Keithley2kDMM.db
DB += Keithley2kDMM_mf40.db
DB += Keithley2kDMM_mf.db
DB += Keithley65xxEM.db
DB += KeithleyDMM.db
DB += Kepco_BOP.db
DB += LakeShore330.db
DB += LakeShore331.db
DB += LakeShore335.db
DB += LakeShore336.db
DB += LakeShore340.db
DB += LakeShoreDRC-93CA.db
DB += MitutoyoMIG2.db
DB += MKS651C.db
DB += MKS.db
DB += MKS_single.db
DB += MPC.db
DB += NCD_R2X.db
DB += NeslabEX.db
DB += Newport_LAE500.db
DB += Omega_DP41.db
DB += OmegaDP41.db
DB += Oxford_ILM202.db
DB += Oxford_X1k.db
DB += PACE5000.db
DB += Pelco_CM6700.db
DB += Pelco_CM6700_names.db
DB += PHD2000.db
DB += PI500.db
DB += picoMotor.db
DB += picoStop12.db
DB += picoStop8.db
DB += pzt.db
DB += serial.db
DB += serialFmt.db
DB += SR570.db
DB += SR630.db
DB += Tabor8024.db
DB += TPG261.db
DB += TSP.db

REQ += ADAM_4018_chan_settings.req
REQ += ADAM_4018_settings.req
REQ += Agilent_E3631A_settings.req
REQ += Agilent_settings.req
REQ += asynRecord_settings.req
REQ += BK9130_settings.req
REQ += BK9173B_settings.req
REQ += CPSyringe_settings.req
REQ += deviceCmdReply_settings.req
REQ += Encoder_AD4_settings.req
REQ += Eurotherm2k_settings.req
REQ += HG-100_settings.req
REQ += Keithley_10CH_settings.req
REQ += Keithley2kDMM20_settings.req
REQ += Keithley2kDMM_channelN_settings.req
REQ += Keithley2kDMM_mf10_settings.req
REQ += Keithley2kDMM_mf20_settings.req
REQ += Keithley2kDMM_mf22_settings.req
REQ += Keithley2kDMM_mf40_settings.req
REQ += Keithley2kDMM_mf_channelN_settings.req
REQ += Keithley2kDMM_settings.req
REQ += LakeShore330_settings.req
REQ += LakeShore331.req
REQ += LakeShore335.req
REQ += LakeShore336.req
REQ += LakeShore340.req
REQ += MKS651C_settings.req
REQ += MPC_settings.req
REQ += Newport_LAE500_settings.req
REQ += Omega_DP41_settings.req
REQ += PACE5000_settings.req
REQ += Pelco_CM6700_settings.req
REQ += PHD2000_settings.req
REQ += picoMotor_positions.req
REQ += picoMotor_settings.req
REQ += SR570preamp_settings.req
REQ += SR570_settings.req
REQ += SR630_settings.req
REQ += SR830_settings.req
REQ += Tabor8024_settings.req
REQ += TSP_settings.req
REQ += USdigital_T7_settings.req
REQ += USdigital_X3_settings.req


#----------------------------------------------------
# If <anyname>DB += .db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
